name: Prepare Release Branch

on:
  push:
    branches:
      - release

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare-release-branch:
    name: Prepare Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - name: Run changeset version
        run: npm run version-packages

      - name: Commit and Push Changelog and Bump Versions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "chore(release): version bump and changelog"
          git push origin release