name: Create Pull Request on Push
on:
  push:
    branches:
      - 'feature/**'
permissions:
  contents: write
  pull-requests: write
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main
          title: 'Pull request automático após push na branch ${{ github.ref_name }}'
          body: |
            Este pull request foi criado automaticamente após um push na branch ${{ github.ref_name }}.
            Mais detalhes sobre as alterações podem ser encontrados no commit.
          commit-message: 'feat: Adiciona pull request automático após push'
      - name: Check PR URL
        if: steps.create_pr.outputs.pull-request-number != ''
        run: |
          echo "Pull request criado: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "Número do pull request: ${{ steps.create_pr.outputs.pull-request-number }}"
